### ISSUE TITLE
Windows 10 x64 Hanging

### ISSUE THREAD

**Issue by HaydonHall** [falahati/NVIDIASurroundToggler#10]
I'm grateful this is out there as Surround won't engage without disengaging shortly after mysteriously with Nvidia's control panel. This makes the shortcut keys stick, but all the other really nifty context features seem to hang when I try to apply them even in admin mode. I'm using Win 10 x64 with an Nvidia 970. Thank you for dedicating your time to this project.

I'm also using a pair of Dell H2415's.

**Comment by falahati** [comment]
Hey @haydonhall,
Can you please descripe the problem more clearly? Which options make the program hang and in which part of program execution?
Thanks

**Comment by HaydonHall** [comment]
Here is a better description.

I can't apply any of the context features whatsoever. They just hang indefinitely even when I try to run/apply them. I even tried installing the "install.exe" by right-clicking and choosing run admin. Thanks again and I appreciate your immediate response.

**Comment by falahati** [comment]
So if you open the program by start menu, it works, but if you right click on desktop and select "Toggle Surround Mode" it hangs. Am I correct? And by hangs you mean that the program never opens or it does but it hangs on white screen later on?

**Comment by HaydonHall** [comment]
If I right click on my desktop>NVIDIA Surround>Toggle Surround Mode

It tries to load with this in the background ...Don't move your mouse or
touch your keyboard...this is serious business....and it locks up and the
only way is to Control+Alt+Delete to go to Task Manager to Close the
process to get back to my desktop. I've given it minutes and it just hangs
on that screen. I have a fairly fast machine.

Sorry for not explaining this adequately.....

**Comment by falahati** [comment]
If it works when opened through start menu and not from context menu, its a strange behavior.

What is your Windows' UI and NVidia Control Panel language? Is it in English?

**Comment by HaydonHall** [comment]
I can't seem to find the entry in the start menu. I was using the context
menu to save steps from switching from normal to surround during gaming.
It's in English.

**Comment by HaydonHall** [comment]
Found the entry in the start menu and it exhibits the exact same behavior.
Thank you.
