### ISSUE TITLE
Is is possible to get a 3rd toggle

### ISSUE THREAD

**Issue by kurosov** [falahati/NVIDIASurroundToggler#11]
for single display mode? Some games go iffy with multiple monitor systems, especially if you decide to push the extra horsepower to DSR instead of surround and a 3rd toggle to automatically disable two of the monitors in NVCP would make this tool even more useful.

**Comment by falahati** [comment]
it is possible to set the extended mode for one monitor only as far as I remember. So Surround, and One Monitor

Anything more then that with the possibility to switch between monitor settings means that I need to write another program named "Monitor Profile Toggler", not "Surround Toggler". Now the questions is, isn't there any other program doing so already?

**Comment by falahati** [comment]
After a quick search:
http://www.realtimesoft.com/ultramon/overview/
www.nirsoft.net/utils/multi_monitor_tool.html
https://sourceforge.net/projects/monitorswitcher/

In fact the first one I believe is able to even enable and disable surround, not tested tho, and not free
But others are free and can be used side by side with this tool
