### ISSUE TITLE
Toggling into extended mode crashes computer (restart required).

### ISSUE THREAD

**Issue by kareemill** [falahati/NVIDIASurroundToggler#12]
I apologise for the similarities to the other issues but the other posters didn't seem very helpful. 

Toggling into surround mode works. The setting is saved correctly by the program and everything is perfect.

Toggling back from surround mode into desktop extended causes the computer to hang on the white please wait screen if a setting is saved. The saved setting should be an extended desktop (as that was it was when it was saved) but when the program crashes only desktop 2 (my main monitor) is shown. Upon restarting, only desktop 2 is displayed however changing into extended mode by either win + p shortcut or through display in the control panel immediately restores the correct resolutions and display positions.

If when toggling back into desktop extended no setting is saved the program executes correctly and the control panel is shown at the end where, again, changing the appropriate drop down to extended restores everything perfectly. This is the current work around I am using (deleting the extended setting after I toggle into surround mode ).

I am on Windows 10 64 Bit. English UK as the language, with 2 monitors (at different resolutions). No SLI and latest nVidia drivers (non beta) for my GTX 980.

**Comment by falahati** [comment]
So the program crashes while restoring extended settings and as result you need to do that part manually. How does the program crash? Any error message?

**Comment by kareemill** [comment]
No error. Crashes on please wait screen such that computer responds to no other commands ctrl+alt+del for example does nothing. I have to manually power down computer from the off switch. 

Thank you for the program anyway. It's a vital bit missing from nvidia surround.

**Comment by falahati** [comment]
Well, In that case, I have no idea what's happening. Probably some problem on Windows side or invalid API calling of a sort.

If anyone having the same problem can provide me with Team Viewer access and with Visual Studio Community edition installed, I can narrow down the issue to a piece of code and then hopefully I can fix it.
