### ISSUE TITLE
Dark mode for eye problems

### ISSUE THREAD

**Issue by DimaClaudiu** [falahati/NVIDIASurroundToggler#14]
I want to thank you for this amazing program, work like a charm a lot of time saved, but I have a little problem with it. The white background that appears when I toggle between modes. I have 3 monitors and also an eye problem and when I try to switch, especially at night so much white light coming out at once hurts.
I managed to fix the problem by changing Back Color in SplashForm.cs 40,40,40 seems a nice value, however I don't know how to create a setup, install and use this modified version from R-click context menu.

Can you provide any help or tips regarding this? Thank you!

EDIT: Fixed it myself.

**Comment by falahati** [comment]
Well good point, but I chose white to stops the flashes happens by opening and closing nVidia Control Panel. You had no problem with those?

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
