### ISSUE TITLE
Not working at all for me

### ISSUE THREAD

**Issue by nycqns983** [falahati/NVIDIASurroundToggler#15]
Thanks so much for creating this app!

The problem (for me) is that its not working at all for me. :(

I hit the "toggle surround mode" button and then, the screens go white, it asks me to not touch the mouse or keyboard... and then, once it finishes, its the same as it was before.

It wont switch modes...wont do anything except for the white screen.

What am I doing wrong?

Thanks!

**Comment by gordislav** [comment]
Same here, 
After ~30 seconds of white screens with 'don't tuch...' message, nothing happens and the mode stays unchanged. Tried toggling from extended to surround and the other way around...

Intel Core i5 3570K @ 3.40GHz
Windows 10 Pro 64-bit (OS Build 14393.321)
NVIDIA GTX 970
GeForce driver 373.06
3x 1080p monitor

**Comment by nycqns983** [comment]
Hopefully someone is able to find a fix for this :)

**Comment by falahati** [comment]
Well it should at least show some error message. I checked the code and I cant find a path that leaves you without any error message.

But I am willing to test the application on your systems if you can provide Team Viewer access with Visual Studio Community installed.

**Comment by Xanadou** [comment]
yesterday I had a similar problem. When I was toggling I got the same like the others. But I got an error message. I haven´t the correct message now, but there was a hint that nvidia not found. I deinstalled the driver an installed it new (373.06). -> the problem was soved.
I hope it helps ;)

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
