### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thekidy** [falahati/NVIDIASurroundToggler#16]
when toggling to surround, i get this error

![yeah](https://cloud.githubusercontent.com/assets/23108165/19785151/3867b2a4-9c4d-11e6-85d7-8075f8e5118d.png)

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
