### ISSUE TITLE
Cannot find the surround settings

### ISSUE THREAD

**Issue by widewing** [falahati/NVIDIASurroundToggler#17]
It's Chinese language here, and the configure item is "配置 Surround 、PhysX"

**Comment by falahati** [comment]
Can you post a picture of this page in Control Panel?

**Comment by widewing** [comment]
![image](https://cloud.githubusercontent.com/assets/4755389/23023766/fdc053c0-f491-11e6-8292-e21e881775e5.png)

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
