### ISSUE TITLE
Extended mode is not remembered

### ISSUE THREAD

**Issue by astearon** [falahati/NVIDIASurroundToggler#18]
Every time i set my extended mode then trigger the surround from your tool it will not remember the extended setup.
When returning from surround to extended i only end up with the left most screen on and at the wrong resolution.
I have tried to clear what the tool remembers as the extended setup, re-made my original screen resolutions and orientations then triggered the surround but even then, when going back, i end up with only 1 screen at wrong rez.

**Comment by falahati** [comment]
Interesting. This tool asks windows about its settings and then tries to apply them. What is your setup and arrangements? How many GPU and screen? All same resolution? Are they all connected to one GPU? And your Windows version.

**Comment by astearon** [comment]
One 1070 GPU with latest drivers
3 screens with wide 1080 side screens and a square 1024 center one
All connected to the same GPU.
Sides connected via HDMI and DP and center one via DVI
Windows 10 pro anniversary ed.

As a side note...this is the same thing that happens when manually disabling surround. 
That's actually the reason i wanted the tool..so i'd need not redo the setup every time i disable it.

**Comment by falahati** [comment]
I think the reason behind it the center screen having a different resolution. We had a similar issue last year with another user having a similar configuration. I will take a look at it.

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
