### ISSUE TITLE
4th monitor on second video card

### ISSUE THREAD

**Issue by SteeveGL** [falahati/NVIDIASurroundToggler#19]
3 monitors in surround mode (Nvidia) + 1 in extended (ATI)

I this case, the program seems to do nothing. I don't know if they are logs somewhere to help you out?

![image](https://cloud.githubusercontent.com/assets/6455947/23406624/dd491618-fd8d-11e6-946d-579206d10a02.png)

**Comment by falahati** [comment]
Currently this is not possible. Please wait for the next version of the program releasing in next few weeks.

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
