### ISSUE TITLE
Bezel correction value not applied

### ISSUE THREAD

**Issue by morbna** [falahati/NVIDIASurroundToggler#20]
Nvidia driver 378.49. using 3 1920x1080 monitors.
When toggling surround mode, bezel corrected resolution of 6000x1080, as configured, is not applied.
default 5760x1080 is used instead.
also, not sure if even supported, but the icons are getting messed up every time i toggle between modes.
Thanks.

**Comment by falahati** [comment]
Known issue #13 , please wait for the next release.

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
