### ISSUE TITLE
Fatal Error: Can't find the surround settings

### ISSUE THREAD

**Issue by f00d4tehg0dz** [falahati/NVIDIASurroundToggler#21]
Hi There!
I received this error while trying out the Toggle function.  I do have SLI. So perhaps thats why?
![captures](https://cloud.githubusercontent.com/assets/1635526/26072191/b798bbd6-3978-11e7-87ab-de6efbe1701e.PNG)
As you can see I already have Surround Mode enabled. So not sure whats going on here. 
I'm using version 382.05 
![capturesd](https://cloud.githubusercontent.com/assets/1635526/26072193/b7c43f04-3978-11e7-844d-f5055fcc14e2.PNG)

Thoughts?

**Comment by falahati** [comment]
Hey,

Unfortunately, this project as for now is out of date so there is no support for it.

However, there is another project that I am working on that achieves the same thing with a different method and it is not yet completed. But if you are interested in testing that, I can provide you with a link to the beta version of it. So you can check it out early and also inform me of any possible bugs or problems.

**Comment by f00d4tehg0dz** [comment]
Thanks for the reply.

Sure! I'll definitely test it out for you and report back and bugs/issues.

**Comment by ZeseAgapen** [comment]
I too would like the link to test and report. Thanks

**Comment by falahati** [comment]
Well, this is nowhere complete and needs a lot of changes both in functionality and especially in UI/UX.
Also, a lot of goodies are missing like the tray icon, hotkey registration, and the shell extension. So lower your expectations, please :)

Also, for now, you can't edit the topology, all you can do is to save the current topology and switch between them. So you first need to open the program and clone current arrangement of your displays, then enable the surround from the nVidia control panel and create a profile based on the new arragment. 

At this moment you should be able to switch between these profiles or create a desktop shortcut for each one.

Following is the binary files of the current build. I am going to publish the source code in the next days or a week.

Thanks for testing it out.
[FILE REMOVED]

**Comment by f00d4tehg0dz** [comment]
Thanks! I'll start trying it out ASAP

**Comment by strangersdad** [comment]
I have just signed up to say Thank you
I have tested loads of programs to be able to jump in and out of Nvidia surround on my four screen setup
and this is the only one that worked.

THANK YOU

**Comment by falahati** [comment]
So any bug or success story?

**Comment by robibla** [comment]
Here's some feedback on DisplayProfileSwitcher.zip  after testing for a bit:
It seemed to capture profiles successfully, and is able to flawlessly recall the "extended" display setup (taking me **out** of surround mode).  I can't seem to get it to recall the Surround profile however.  Setting up the extended displays again after using surround was always the most tedious part of switching profiles though though, so I'm still finding this quite helpful.  

Thanks! Keep up the good work.

**Comment by assetto** [comment]
Done!! You are the man!! Works like a charm!!!
It is even ready before 30secs are done counting.

**Comment by falahati** [comment]
Hey,

The latest version (still beta) is available through the following link:
https://github.com/falahati/HeliosDisplayManagement/releases/

Please consider reporting bugs and issues at the new project's issue tracker located here:
https://github.com/falahati/HeliosDisplayManagement/issues/

This thread is now closed.

Thanks
