### ISSUE TITLE
How to use toggler

### ISSUE THREAD

**Issue by iDarkXY** [falahati/NVIDIASurroundToggler#22]
Hello

I am sorry but I couldn't figure out at all how to use this tool properly but I am very grateful that it exist. Thanks to the program, I managed to enter  surround mode but how can I switch easily between extended mode and surround mode? Can I configure a keyboard shortcut to switch between the modes? 

I saw in the tools options that I can "place shortcut" but then I have to enter a *.ink file. What is the purpose of this? Unfortunately, I don't find it very intuitiv to use.

**Comment by falahati** [comment]
Hey,

This repo is out of date and I didn't have the time to push the new updates, however, there is a compiled alpha stage program that can be downloaded from my post in issue #21 that is capable of switching between multiple modes. Try that.

PS: a .ink file is a shortcut file, but their extension is hidden in Windows. And as you don't see the extension usually when working with Windows, I believe you misunderstood how it works. Just enter a name and it will place the shortcut, then simply use the shortcut for the fast switch.
