### ISSUE TITLE
Extend fails to activate all screens

### ISSUE THREAD

**Issue by assetto** [falahati/NVIDIASurroundToggler#23]
Hi since some weeks my extend does not work properly anymore. It looks like some new nvidia updates destroyed it.
I can succesfully put it to surround mode. When I switch back to extended mode it fails to recoqnize all screens (triple). Then I have to manually activate one of the screens to get it running again.

Please advice.

**Comment by falahati** [comment]
Please check out the link I posted on the #21, and report back. Tnx

**Comment by falahati** [comment]
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.
