### ISSUE TITLE
Does not appear to work in modern systems.

### ISSUE THREAD

**Issue by actualcannibal** [falahati/NVIDIASurroundToggler#24]
Installs fine, but does not run successfully. Error states "Nvidia Control Panel is not installed on the system!"

I believe this error is because the Nvidia Control Panel is now installed through the Microsoft Store, instead of through the installer on Nvidia's website.

**Comment by falahati** [comment]
Please read the readme:

> THIS PROJECT IS CURRENTLY OUTDATED AND MAY NOT WORK AS EXPECTED. IT IS ALSO NOT UNDER ACTIVE DEVELOPMENT OR MAINTENANCE ANYMORE.
> 
> Please consider checking out my other project that should do what this project intended to do, even better: https://github.com/falahati/HeliosDisplayManagement

then read the readme of the other project
