### ISSUE TITLE
Nvidia is not on C: 

### ISSUE THREAD

**Issue by labtreeo** [falahati/NVIDIASurroundToggler#3]
Hey,

I have my nvidia installed on my other drive is there a way to change your program so it is looking in the right drive I think that is the reason why it's not working for me

Thanks in advance

**Comment by johnbe2** [comment]
yes, select Tools > Options and point to the setup directory. Please note,
that setups must be in the standard directory structure or they will not be
found.

John

**Comment by labtreeo** [comment]
Thanks for the quick response but it didn't work sadly enough here is a picture of the error i get maybe you can figure it out

Thanks in advance

![naamloos](https://cloud.githubusercontent.com/assets/17197450/14504536/8b80721a-01b5-11e6-9fb3-958123fe9849.png)

**Comment by falahati** [comment]
Hi, what is your windows language?

**Comment by labtreeo** [comment]
dutch is that the problem because i can't change it unless i install a new windows

**Comment by falahati** [comment]
Yeah, unfortunately, the current version of the program only works with English version of the NVidia Control Panel. Can you download the English version of the NVidia ControlPanel/Drivers from their website? Not sure if its going to help; but it is the only way I can think of now that may works without changing the Windows' language.

**Comment by falahati** [comment]
Hey labtreeo,
Can you give me two screenshots from the NVIDIA Control panel and the Surround Dialog? If possible to type me the title of the windows (both of them) and the phrase "Disable" in your language I may be able to add your language to the app.

**Comment by labtreeo** [comment]
That would be amazing, But i'm not entirely clear on what surround dialog you mean

**Comment by falahati** [comment]
These parts: (With the exception of the button, I want the "Disable Caption")
http://imgur.com/LmZmIQw

**Comment by labtreeo** [comment]
Here are is the picture the language is dutch i wasnt able to get the popup box but is says in dutch "weet uw zeker dat u nvidia surround wilt uitschakelen" uitschakelen means disable by the way.

![naamloos](https://cloud.githubusercontent.com/assets/17197450/14588636/4652f700-04ce-11e6-8369-28b0b8262002.png)

**Comment by falahati** [comment]
Uninstall the older version and then try this one:
https://github.com/falahati/NVIDIASurroundToggler/releases/tag/v1.1.1

**Comment by labtreeo** [comment]
Thanks man for all the help this works. their is just one slight problem my pc crashes when i try to deactivate surround it does this when i manually turn it of aswell so this is not a problem with your software just nvidia software being a dick nicely said :)

Thanks again

**Comment by falahati** [comment]
Glad it helped. Closed
