### ISSUE TITLE
Not working on monitors different sizes

### ISSUE THREAD

**Issue by jLynx** [falahati/NVIDIASurroundToggler#4]
So was excited to try this but sadly it didn't work. I assume its because all 3 of my monitors are different sizes

**Comment by falahati** [comment]
Well that should not be the problem. Please explain exactly what happens.

**Comment by jLynx** [comment]
I open the program, it shows the dont touch mouse or keyboard message, then it has the control panel pop up for a few seconds, then they white screen is back, then it closes and im still extended. (I then run it again and same story)

**Comment by falahati** [comment]
Please post a screenshot from your control panel's "Surround" page.

**Comment by jLynx** [comment]
![image](https://cloud.githubusercontent.com/assets/4393979/14913910/5292e724-0e5a-11e6-8548-b3c976611a33.png)

**Comment by jLynx** [comment]
Is that what you needed?

**Comment by jLynx** [comment]
Hello?

**Comment by falahati** [comment]
Well that's unusual. I cant see a quiet exit from the program line at that point. It should either change the checkbox status and click apply (which opens the Surround Set Up Window) or shows an error message. No matter what is the setup of your system. The only quiet exit from the logical line of the program at this point is when you are already in surround mode which based on your screen shot is not the case.
Try opening the "Settings" form and clear all settings there. Then check again to see if you get the "Surround Set Up" page at all.
And tell me if I missed something. Any thing that happens other than this, that I don't know.

**Comment by falahati** [comment]
#15
