### ISSUE TITLE
Stuck on white screen (please do not touch)

### ISSUE THREAD

**Issue by ghost** [falahati/NVIDIASurroundToggler#5]
I have 4 monitors, 3 in surround and 1 on top. Will stay stuck on the white screen consistantly.
Windows 10 with latest update x64

**Comment by falahati** [comment]
Hi,
In which direction it does stuck? When switching to Surround or Extended? 
If in switching to surround, does it show the surround setup page? (Try removing the configuration using the Setting first)
And what do you exactly mean by stuck? do you need to restart your computer to get rid of it?
