### ISSUE TITLE
French support

### ISSUE THREAD

**Issue by ObiYoann** [falahati/NVIDIASurroundToggler#6]
Hi!
I would like to help include support for french, i cloned the repository locally and tried to add the required modifications but i can't figure the strings we should have in the ressource file.
Right now i have :

```
  <data name="NVIDIA_ControlPanel_Caption_NVIDIA_Control_Panel" xml:space="preserve">
    <value>Panneau de configuration NVIDIA</value>
  </data>
  <data name="NVIDIA_Surround_Caption_NVIDIA_Set_Up_Surround" xml:space="preserve">
    <value>Configuration du Surround NVIDIA</value>
  </data>
  <data name="NVIDIA_Surround_DisableButton_Disable" xml:space="preserve">
    <value>Désactiver</value>
  </data>
```

But it is not working, it does not find the window it searches for.
It is raising this exception :

```
        private static bool AutomateControlPanel(Application application, bool? goSurround)
        {
            var window = application.GetWindow(NVidiaLocalization.NVIDIA_ControlPanel_Caption_NVIDIA_Control_Panel);
            try
            {
                //window.HideMinimize(); // Hiding also applies the settings we want
                var surroundTreeItem = window.GetChildWindowWithControlId<UIItem>(4100, 5000);
                if (surroundTreeItem == null)
                {
>>                    throw new Exception(Language.Surround_Can_t_find_the_surround_settings);
                }
```

I am confident about the first one, found within the context menu on the desktop.
I am not so sure about the two other labels.
Here is a screenshot of the nvidia control panel in french :
![image](https://cloud.githubusercontent.com/assets/448538/15008883/8ea0a738-11e3-11e6-9abe-b2ef46996f16.png)

My setup is kind of tricky, as i have two displays i use most of the time, and 3 other displays i use when i want to game. One of the limitation i have with the GTX980ti is that it can't handle more than 4 displays at once, so i need to disable my 2 main displays when i enable the surround ones, and i need the reenable the two displays after i disable the surround.
Currently, when i do this manually, when i enable the surround i need to rearrange the surround displays but it auto disables the other ones. I always need to recorrect bezels.
When i disable surround manually, i shuts down all displays but the left one of my surround setup.
I need then to manually disable it, reenable the two main displays et rearrange them.
If only we could have profiles as we have been able to do with AMD card for years......
Thanks for your help and congrats for your awesome work already! ;)

**Comment by falahati** [comment]
Hi,
Can you open the surround configuration page and take a screen shot? Just check the "Etendre affichages avec surround" button and click "Configurer". Then take a picture.

Thanks

**Comment by falahati** [comment]
Never mind the last reply.
Your strings seems correct. Can you check the latest release? v1.2
And yeah, it should be able to memorize your config and revert back to it.

**Comment by falahati** [comment]
This is now a part of the latest release:
https://github.com/falahati/NVIDIASurroundToggler/releases/tag/v1.2.1

**Comment by ObiYoann** [comment]
Thanks a lot for your help, i haven't been able to follow up or test the new releases as i have been waiting for a long time for my GTX to come back from RMA (i'm using an aging radeon 6970 right now... :/).
I'll let you know once i can test it.
