### ISSUE TITLE
Add bezel correction support

### ISSUE THREAD

**Issue by ghost** [falahati/NVIDIASurroundToggler#7]
No matter what I do, when switching to Surround on a clean try (clicked the "clear surround" button thing in options) it won't perform bezel correction. It just enables surround.

Can we have bezel correction? :)

**Comment by falahati** [comment]
Thanks for reporting
Fixed in latest commit and will be a part of the next release. Meantime, you can compile the latest source code if you are in hurry.

**Comment by falahati** [comment]
This is now a part of the latest release:
https://github.com/falahati/NVIDIASurroundToggler/releases/tag/v1.2.1
