### ISSUE TITLE
Fatal Error : Can't find the surround settings

### ISSUE THREAD

**Issue by lamskaka** [falahati/NVIDIASurroundToggler#8]
Hello,

Thank you for your software but I have a problem.
I used V1.2 and in option i changed language : french

I launch 'Toggle Nvidia Surround' and when it's finished i have this message : 'Fatal Error : Can't find the surround settings'.

My Surround is configured.
Where is the problem?

OS : Windows 10 64bits
Nvidia version : 368.39

Thanks for your help.

![tns_000](https://cloud.githubusercontent.com/assets/20014999/16171800/373df19e-3579-11e6-8c53-a87512fec020.PNG)
![tns_001](https://cloud.githubusercontent.com/assets/20014999/16171802/373e8a1e-3579-11e6-8cb0-5aa0164c55c1.PNG)
![tns_002](https://cloud.githubusercontent.com/assets/20014999/16171803/373eb50c-3579-11e6-842a-000e60c0185e.PNG)
![tns_003](https://cloud.githubusercontent.com/assets/20014999/16171801/373e484c-3579-11e6-9222-3cd807fd787b.PNG)

**Comment by stann84** [comment]
i have same problem

**Comment by falahati** [comment]
Well, the only problem is that I cant find the real issue with this one until I have access to your computers.
So unless someone is willing to give me team viewer access, I am afraid that I can not solve this problem.

**Comment by stann84** [comment]
i send you an email

**Comment by nklink45** [comment]
Hi, I have exactly the same problem, my system language is french and nvidia driver too. Did you found a solution? Thanks a lot^^

**Comment by falahati** [comment]
This should be fixed in the latest release:
https://github.com/falahati/NVIDIASurroundToggler/releases/tag/v1.2.1
