### ISSUE TITLE
Bezel correction value, not applied.

### ISSUE THREAD

**Issue by sharonna511** [falahati/NVIDIASurroundToggler#9]
Hello

When switching to surround it does not active the bezel correction.
I inputed it during first time setting, also retried several times.
The value is correctly stored in the user.config file, but it does not activate it.

My NV control panel is default in German language, i delete the regional files to have it in english, but i already tried it in german too, no success.
My OS is Windows 7 x64, nvidia driver version 368.39.

Thanks for this tool and your help!

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <NVIDIASurroundToggle.Properties.Settings>
            <setting name="Arrangement" serializeAs="String">
                <value>MosaicDisplay ONKYO Corporation TX-NR515|MosaicDisplay Samsung SA300/SA350 (2 von 2)|MosaicDisplay Samsung SA300/SA350 (1 von 2)</value>
            </setting>
            <setting name="Topology" serializeAs="String">
                <value>1</value>
            </setting>
            <setting name="Resolution" serializeAs="String">
                <value>1</value>
            </setting>
            <setting name="RefreshRate" serializeAs="String">
                <value>0</value>
            </setting>
            <setting name="Bezel1" serializeAs="String">
                <value>110</value>
            </setting>
            <setting name="Bezel2" serializeAs="String">
                <value>110</value>
            </setting>
            <setting name="Bezel3" serializeAs="String">
                <value>0</value>
            </setting>
            <setting name="Bezel4" serializeAs="String">
                <value>0</value>
            </setting>
            <setting name="DisplaySettings" serializeAs="String">
                <value>&lt;?xml version="1.0" encoding="utf-16"?&gt;&lt;ArrayOfDisplaySetting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DisplaySetting&gt;&lt;Devmode&gt;&lt;DeviceName&gt;cdd&lt;/DeviceName&gt;&lt;SpecVersion&gt;1025&lt;/SpecVersion&gt;&lt;DriverVersion&gt;1025&lt;/DriverVersion&gt;&lt;Size&gt;124&lt;/Size&gt;&lt;DriverExtra&gt;0&lt;/DriverExtra&gt;&lt;Fields&gt;Position DisplayOrientation LogPixels BitsPerPixel PelsWidth PelsHeight DisplayFlags DisplayFrequency&lt;/Fields&gt;&lt;Position&gt;&lt;X&gt;1920&lt;/X&gt;&lt;Y&gt;0&lt;/Y&gt;&lt;/Position&gt;&lt;DisplayOrientation&gt;0&lt;/DisplayOrientation&gt;&lt;DisplayFixedOutput&gt;0&lt;/DisplayFixedOutput&gt;&lt;Color&gt;Unknown&lt;/Color&gt;&lt;Duplex&gt;Unknown&lt;/Duplex&gt;&lt;YResolution&gt;0&lt;/YResolution&gt;&lt;TTOption&gt;0&lt;/TTOption&gt;&lt;Collate&gt;Off&lt;/Collate&gt;&lt;FormName /&gt;&lt;LogPixels&gt;0&lt;/LogPixels&gt;&lt;BitsPerPel&gt;32&lt;/BitsPerPel&gt;&lt;PelsWidth&gt;1920&lt;/PelsWidth&gt;&lt;PelsHeight&gt;1080&lt;/PelsHeight&gt;&lt;DisplayFlags&gt;0&lt;/DisplayFlags&gt;&lt;Nup&gt;0&lt;/Nup&gt;&lt;DisplayFrequency&gt;60&lt;/DisplayFrequency&gt;&lt;/Devmode&gt;&lt;DisplayName&gt;\\.\DISPLAY1&lt;/DisplayName&gt;&lt;/DisplaySetting&gt;&lt;DisplaySetting&gt;&lt;Devmode&gt;&lt;DeviceName&gt;cdd&lt;/DeviceName&gt;&lt;SpecVersion&gt;1025&lt;/SpecVersion&gt;&lt;DriverVersion&gt;1025&lt;/DriverVersion&gt;&lt;Size&gt;124&lt;/Size&gt;&lt;DriverExtra&gt;0&lt;/DriverExtra&gt;&lt;Fields&gt;Position DisplayOrientation LogPixels BitsPerPixel PelsWidth PelsHeight DisplayFlags DisplayFrequency&lt;/Fields&gt;&lt;Position&gt;&lt;X&gt;0&lt;/X&gt;&lt;Y&gt;0&lt;/Y&gt;&lt;/Position&gt;&lt;DisplayOrientation&gt;0&lt;/DisplayOrientation&gt;&lt;DisplayFixedOutput&gt;0&lt;/DisplayFixedOutput&gt;&lt;Color&gt;Unknown&lt;/Color&gt;&lt;Duplex&gt;Unknown&lt;/Duplex&gt;&lt;YResolution&gt;0&lt;/YResolution&gt;&lt;TTOption&gt;0&lt;/TTOption&gt;&lt;Collate&gt;Off&lt;/Collate&gt;&lt;FormName /&gt;&lt;LogPixels&gt;0&lt;/LogPixels&gt;&lt;BitsPerPel&gt;32&lt;/BitsPerPel&gt;&lt;PelsWidth&gt;1920&lt;/PelsWidth&gt;&lt;PelsHeight&gt;1080&lt;/PelsHeight&gt;&lt;DisplayFlags&gt;0&lt;/DisplayFlags&gt;&lt;Nup&gt;0&lt;/Nup&gt;&lt;DisplayFrequency&gt;60&lt;/DisplayFrequency&gt;&lt;/Devmode&gt;&lt;DisplayName&gt;\\.\DISPLAY2&lt;/DisplayName&gt;&lt;/DisplaySetting&gt;&lt;DisplaySetting&gt;&lt;Devmode&gt;&lt;DeviceName&gt;cdd&lt;/DeviceName&gt;&lt;SpecVersion&gt;1025&lt;/SpecVersion&gt;&lt;DriverVersion&gt;1025&lt;/DriverVersion&gt;&lt;Size&gt;124&lt;/Size&gt;&lt;DriverExtra&gt;0&lt;/DriverExtra&gt;&lt;Fields&gt;Position DisplayOrientation LogPixels BitsPerPixel PelsWidth PelsHeight DisplayFlags DisplayFrequency&lt;/Fields&gt;&lt;Position&gt;&lt;X&gt;-1920&lt;/X&gt;&lt;Y&gt;0&lt;/Y&gt;&lt;/Position&gt;&lt;DisplayOrientation&gt;0&lt;/DisplayOrientation&gt;&lt;DisplayFixedOutput&gt;0&lt;/DisplayFixedOutput&gt;&lt;Color&gt;Unknown&lt;/Color&gt;&lt;Duplex&gt;Unknown&lt;/Duplex&gt;&lt;YResolution&gt;0&lt;/YResolution&gt;&lt;TTOption&gt;0&lt;/TTOption&gt;&lt;Collate&gt;Off&lt;/Collate&gt;&lt;FormName /&gt;&lt;LogPixels&gt;0&lt;/LogPixels&gt;&lt;BitsPerPel&gt;32&lt;/BitsPerPel&gt;&lt;PelsWidth&gt;1920&lt;/PelsWidth&gt;&lt;PelsHeight&gt;1080&lt;/PelsHeight&gt;&lt;DisplayFlags&gt;0&lt;/DisplayFlags&gt;&lt;Nup&gt;0&lt;/Nup&gt;&lt;DisplayFrequency&gt;60&lt;/DisplayFrequency&gt;&lt;/Devmode&gt;&lt;DisplayName&gt;\\.\DISPLAY3&lt;/DisplayName&gt;&lt;/DisplaySetting&gt;&lt;/ArrayOfDisplaySetting&gt;</value>
            </setting>
            <setting name="FirstRun" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ControlPanelLanguage" serializeAs="String">
                <value />
            </setting>
        </NVIDIASurroundToggle.Properties.Settings>
    </userSettings>
</configuration>`

**Comment by falahati** [comment]
Hi,

This issue has be fixed in the latest commit and as part of a similar report (#7), however as of yet, it is not a part of any public release. You can compile the code from source or wait a little for a new version.

**Comment by falahati** [comment]
This is now a part of the latest release:
https://github.com/falahati/NVIDIASurroundToggler/releases/tag/v1.2.1
